### ISSUE TITLE
ReservationAL.java compile issue

### ISSUE THREAD

**Issue by matts-school-account** [matts-school-account/CS-342-POS-Final-Project#4]
Opened by: Matthew
Assigned to: Brandon

Description: The file ReservationAL.java is not compiling and is saying that the variable reservationList can not be resolved.

**Comment by BGibis** [comment]
LinkedList reservationList was missing from the Github code. Must not have uploaded my files correctly. Should be fixed now. Thanks!

**Comment by matts-school-account** [comment]
Issue was fixed a while ago, I forgot to close this issue. Everything works as intended!
